application:
  kafka:
    topic: "demo-topic"


spring:
  kafka:
    consumer:
      group-id: "test-group"
      bootstrap-servers: "localhost:9092"
      client-id: "demo-consumer"
      auto-offset-reset: earliest
      value-deserializer: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer"




  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration